path: data/SpeechCommands/speech_commands_v0.02
subset:  
  - "backward"
  - "bed"
  - "bird"
  - "cat"
  - "dog"
  - "down"
  - "eight"
  - "five"
  - "follow"
  - "forward"
  - "four"
  - "go"
  - "happy"
  - "house"
  - "learn"
  - "left"
  - "marvin"
  - "nine"
  - "no"
  - "off"
  - "on"
  - "one"
  - "right"
  - "seven"
  - "sheila"
  - "six"
  - "stop"
  - "three"
  - "tree"
  - "two"
  - "up"
  - "visual"
  - "wow"
  - "yes"
  - "zero"


sample_rate: 16000
clip_length: 1.0
n_fft: 400
hop_len: 160
n_mels: 64

learning_rate: 0.003
batch_size: 64
num_workers: 8
persistent_workers: true
prefetch_factor: 2
pin_memory: false
device: "auto"
max_steps: 10000
amp: true
log_period: 200
eval_period: 2000

seed: 42
base_path: "runs"
resume: null # set to str if you are resuming
remote_name: "training-s3-bucket-runpod/test"
cloud_sync: true